version: '3'
services:
  nfs-client:
    image: busybox
    container_name: nfs-client
    privileged: true
    volumes:
      - nfs-volume:/mnt
    command: tail -f /dev/null
    depends_on:
      - nfs
    networks:
      backend:
        # ipv4_address: 172.28.0.3

  nfs:
    image: gists/nfs-server
    container_name: nfs
    privileged: true
    ports:
      - 2049:2049
    environment:
      NFS_DIR: /nfs-share
      NFS_OPTION: "rw,fsid=0,async,no_subtree_check,no_auth_nlm,insecure,no_root_squash"
    volumes:
      - /data/volume/test:/nfs-share
    networks:
      backend:
        # ipv4_address: 172.28.0.2

networks:
  backend:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 172.28.0.0/16
    #       gateway: 172.28.0.1

volumes:
  nfs-volume:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=nfs,nfsvers=4"
      device: ":/"