version: '3'
services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db # Created database

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080